### PR TITLE
Add more send types

### PR DESCRIPTION
**Pull request by Cretezy**

### CODE REVIEW

**Comment by Cretezy** [comment]
Guess PRs don't work with Travis because of no tokens :/

**Comment by tbsf** [comment]
Looks good to me. Thanks for adding these :)

**Comment by Cretezy** [comment]
https://travis-ci.org/davidchua/pymessenger/builds/160484980

You probably need to fix the tests.

**Comment by Cretezy** [comment]
@tbsf You need to publish it to PyPI I think?

**Comment by tbsf** [comment]
@davidchua Can you publish these changes?

**Comment by davidchua** [comment]
Thanks @Cretezy! Being able to send video is awesome!

@tbsf bumped pypi version to 0.0.7.0

https://pypi.python.org/pypi/pymessenger

I'll look into the permissions issue today.

**Comment by davidchua** [comment]
@Cretezy can you add some tests into this PR for the new additions?

**Comment by Cretezy** [comment]
Yeah I'll work on it soon, thanks for publishing!

**Pull request merged**
