### PR TITLE
Add function to get information about user

### PR DESCRIPTION
**Pull request by staszekdev**
Getting information about the user https://developers.facebook.com/docs/messenger-platform/user-profile

### CODE REVIEW

**Comment by tbsf** [comment]
This is already in user_profile

**Comment by Cretezy** [comment]
I agree this is much cleaner implementation than the other.

**Comment by staszekdev** [comment]
Ok, your right, I overlooked this file, sorry for my oversight.

**Comment by Cretezy** [comment]
I'm working on a major restructuring on the project. I have moved the get_user_info into the bot.py. Expect to see this in a few days!

**Comment by Cretezy** [comment]
Check out https://github.com/davidchua/pymessenger/commit/92369a60ea1d436410116f83dd720109ff837447.

**Comment by Cretezy** [comment]
Fixed in #18

**Pull request closed without merging**
